version: "3"

services:
  frontend:
    build:
      context: frontend
    ports:
      - "92:80"
    depends_on:
      - backend
    networks:
      - nginx_proxy

  backend:
    build:
      context: backend
    ports:
      - "8080:8080"
    networks:
      - nginx_proxy

networks:
  nginx_proxy:
    external: true